spring:
  application:
    name: spring_ai
  ai:
    openai:
      api-key: ${API_KEY}
      chat:
        options:
          model: gpt-5.4-nano
          temperature: 0.9
#          maxTokens: 2048
logging:
  level:
    org.springframework.ai:
      chat.client: DEBUG